In [1]:
#Formatting
#The Old Way or the non-existing printf and sprint
#The Pythonic Way: The string method "format"
q = 459
p = 0.098
print(q, p, p * q)
print(q, p, p * q, sep=",")
print(q, p, p * q, sep=" :-) ")

459 0.098 44.982
459,0.098,44.982
459 :-) 0.098 :-) 44.982


In [2]:
#Overloaded % operator for string formatting
print("Art: %5d, Price per unit: %8.2f" % (453, 59.058))

Art:   453, Price per unit:    59.06


In [3]:
# Conversion: Meaning
# d: Signed integer decimal.
# i: Signed integer decimal.
# o: Unsigned octal.
# C: Obsolete and equivalent to 'd', i.e. signed integer decimal.
# x: Unsigned hexadecimal (lowercase).
# X: Unsigned hexadecimal (uppercase).
# e: Floating point exponential format (lowercase).
# E: Floating point exponential format (uppercase).
# f: Floating point decimal format.
# F: Floating point decimal format.
# g: Same as "e" if exponent is greater than -4 or less than precision, "f" otherwise.
# G: Same as "E" if exponent is greater than -4 or less than precision, "F" otherwise.
# #: Single character (accepts integer or single character string).
# r: String (converts any python object using repr()).
# s: String (converts any python object using str()).
# %: No argument is converted, results in a "%" character in the result. 

print("%10.3e"% (356.08977))
print("%10.3E"% (356.08977))
print("%10o"% (25))
print("%10.3o"% (25))
print("%10.5o"% (25))
print("%5x"% (47))
print("%5.4x"% (47))
print("%5.4X"% (47))
print("Only one percentage sign: %% " % ())

 3.561e+02
 3.561E+02
        31
       031
     00031
   2f
 002f
 002F
Only one percentage sign: % 


In [4]:
# Flags
# The general syntax for a format placeholder is
# %[flags][width][.precision]type

# Flag: Maening
# #: Used with o, x or X specifiers the value is preceded with 0o, 0x or 0X respectively.
# 0: The conversion result will be zero padded for numeric values.
# -: The converted value is left adjusted
# +: A sign character ("+" or "-") will precede the conversion (overrides a "space" flag). 
# Note: If no sign (minus sign e.g.) is going to be written, a blank space is inserted before the value.
print("%#5X"% (47))
print("%5X"% (47))
print("%#5.4X"% (47))
print("%#5o"% (25))
print("%+d"% (42))
print("% d"% (42))
print("%+2d"% (42))
print("% 2d"% (42))
print("%2d"% (42))

 0X2F
   2F
0X002F
 0o31
+42
 42
+42
 42
42


In [5]:
# It is not the print() function that does the formatting, but the % operator itself
s = "Price: $ %8.2f"% (356.08977)
print(s)

Price: $   356.09


In [7]:
# The string method "format"
# Syntax: template.format(p0, p1, ..., k0=v0, k1=v1, ...)
# template : a string which contains one or more fields to be replaced (surrounded by curly braces {}). 
# Anything else, which is not contained in curly braces will be literally printed, i.e., without any changes. 
# If a brace character has to be printed, it has to be escaped by doubling it: {{ and }}. 
# If the positional parameters are used in the order in which they are written, the positional argument specifiers inside of the braces can be omitted, so '{} {} {}' corresponds to '{0} {1} {2}'. 
print("First argument: {0}, second one: {1}".format(47,11))
print("First argument: {}, second one: {}".format(47,11))

# But they are needed, if you want to access them in different orders: '{2} {1} {0}'. 

First argument: 47, second one: 11
First argument: 47, second one: 11


In [8]:
print("Second argument: {1}, first one: {0}".format(47,11)) 
print("Second argument: {1:3d}, first one: {0:7.2f}".format(47.42,11))
print("First argument: {}, second one: {}".format(47,11)) 

Second argument: 11, first one: 47
Second argument:  11, first one:   47.42
First argument: 47, second one: 11


In [9]:
# Left and Right Justification
# Option : Meaning
# '<' : The field will be left-aligned within the available space. This is usually the default for strings.
# '>' : The field will be right-aligned within the available space. This is the default for numbers.
print("{0:<20s} {1:6.2f}".format('Spam & Eggs:', 6.99))
print("{0:>20s} {1:6.2f}".format('Spam & Eggs:', 6.99))

Spam & Eggs:           6.99
        Spam & Eggs:   6.99


In [10]:
# '0' : If the width field is preceded by a zero ('0') character, sign-aware zero-padding for numeric types will be enabled.
x = 378
print("The value is {:06d}".format(x))
x = -378
print("The value is {:06d}".format(x))

The value is 000378
The value is -00378


In [13]:
# ',' : This option signals the use of a comma for a thousands separator.
x = 78962324245
print("The value is {:,}".format(x))
x = 5897653423.89676
print("The value is {0:12,.3f}".format(x))

The value is 78,962,324,245
The value is 5,897,653,423.897


In [14]:
# Using dictionaries in “format”
print("The capital of {0:s} is {1:s}".format("Ontario","Toronto"))
print("The capital of {province} is {capital}".format(province="Ontario",capital="Toronto"))
data = dict(province="Ontario",capital="Toronto")
print("The capital of {province} is {capital}".format(**data))
#double ** is used to unpackm the dictionary and pass its key value pairs as arguments

The capital of Ontario is Toronto
The capital of Ontario is Toronto
The capital of Ontario is Toronto


In [15]:
capital_country = {"United States" : "Washington", 
                   "US" : "Washington", 
                   "Canada" : "Ottawa",
                   "Germany": "Berlin",
                   "France" : "Paris",
                   "England" : "London",
                   "UK" : "London",
                   "Switzerland" : "Bern",
                   "Austria" : "Vienna",
                   "Netherlands" : "Amsterdam"}
print("Countries and their capitals:")
for c in capital_country:
    print("{country}: {capital}".format(country=c, capital=capital_country[c]))

Countries and their capitals:
United States: Washington
US: Washington
Canada: Ottawa
Germany: Berlin
France: Paris
England: London
UK: London
Switzerland: Bern
Austria: Vienna
Netherlands: Amsterdam


In [16]:
# Other string methods for Formatting

In [18]:
# center(...)
# S.center(width[, fillchar]) -> str
#Return S centred in a string of length width. Padding is done using the specified fill character. 
#The default value is a space. 
s = "Python"
print(s.center(20))
print(s.center(20,"*"))

       Python       
*******Python*******


In [19]:
# ljust(...)
# S.ljust(width[, fillchar]) -> str 
# Return S left-justified in a string of length "width". Padding is done using the specified fill character. 
# If none is given, a space will be used as default. 
s = "Training"
print(s.ljust(12))
print(s.ljust(12,"*"))

Training    
Training****


In [20]:
# rjust(...)
# S.rjust(width[, fillchar]) -> str
# Return S right-justified in a string of length width. Padding is done using the specified fill character. 
# The default value is again a space.
s = "Programming"
print(s.rjust(15))
print(s.rjust(15, "*"))

    Programming
****Programming


In [21]:
# zfill(...)
# S.zfill(width) -> str
# Pad a string S with zeros on the left, to fill a field of the specified width. 
# The string S is never truncated. This method can be easily emulated with rjust. 
account_number = "43447879"
print(account_number.zfill(12))
print(account_number.rjust(12,"0"))

000043447879
000043447879


In [23]:
# Statistics Module : import statistics
# Averages and measures of central location

# Method : Description
# mean() : Arithmetic mean (“average”) of data.
# harmonic_mean() : Harmonic mean of data.
# median() : Median (middle value) of data.
# median_low() : Low median of data.
# median_high() : High median of data.
# median_grouped() : Median, or 50th percentile, of grouped data.
# mode() : Mode (most common value) of discrete data.

import statistics
from statistics import mean
print(mean([1, 2, 3, 4, 4]))
print(mean([-1.0, 2.5, 3.25, 5.75]))

from fractions import Fraction as F
print(mean([F(3, 7), F(1, 21), F(5, 3), F(1, 3)]))
from decimal import Decimal as D
print(mean([D("0.5"), D("0.75"), D("0.625"), D("0.375")]))

2.8
2.625
13/21
0.5625


In [24]:
import statistics
print(statistics.median([1, 3, 5]))
print( statistics.median([1, 3, 5, 7]))

3
4.0


In [25]:
# statistics.median_low(data)
# Return the low median of numeric data. 
# The low median is always a member of the data set. When the number of data points is odd, the middle value is returned. When it is even, the smaller of the two middle values is returned.

# statistics.median_low(data)
# Return the low median of numeric data. 
# The low median is always a member of the data set. When the number of data points is odd, the middle value is returned. When it is even, the smaller of the two middle values is returned.

# statistics.median_grouped(data, interval=1)
# Return the median of grouped continuous data, calculated as the 50th percentile, using interpolation.

# statistics.mode(data)
# Return the most common data point from discrete or nominal data. The mode (when it exists) is the most typical value, and is a robust measure of central location

import statistics
print(statistics.mode([1, 1, 2, 3, 3, 3, 3, 4]))

3


In [ ]:
# Measures of spread
# Method : Description
# pstdev() : Population standard deviation of data.
# pvariance() : Population variance of data.
# stdev() : Sample standard deviation of data.
# variance() : Sample variance of data.

from statistics import pstdev
print(pstdev([1.5, 2.5, 2.5, 2.75, 3.25, 4.75]))
from statistics import pvariance
print(pvariance([1.5, 2.5, 2.5, 2.75, 3.25, 4.75]))

In [28]:
from statistics import pvariance
from decimal import Decimal as D
from fractions import Fraction as F
print( pvariance([D("27.5"), D("30.25"), D("30.25"), D("34.5"), D("41.75")]))
print( pvariance([F(1, 4), F(5, 4), F(1, 2)]))

24.815
13/72


In [45]:
# Exceptions
x=3
y=4
try:
    x/y
except ZeroDivisionError:
    print("Divisor must not be 0")
except TypeError:
    print("They must be numbers")
except:
    print("Something unspecified went wrong")
else:
    print("Everything worked")


Everything worked


In [46]:
# A Catch All Exception Script
import traceback
try:
    a = 2/0
except Exception as e:
    print(e.__doc__)
    print(traceback.format_exception(e))

Second argument to a division or modulo operation was zero.
['Traceback (most recent call last):\n', '  File "C:\\Users\\CCPC001\\AppData\\Local\\Temp\\ipykernel_19212\\3400254769.py", line 4, in <module>\n    a = 2/0\n        ~^~\n', 'ZeroDivisionError: division by zero\n']


In [47]:
# Classes 
# class myclass(superclass):
#    def __init__(self,args):
#    def functionname(self,args):
# __init__(self,args) – class constructor
# __del__(self) – class destructor (rarely used)
# classname.functionname() – to access a class function


In [48]:
class Employee:
   'Common base class for all employees'
   empCount = 0

   def __init__(self, name, salary):
      self.name = name
      self.salary = salary
      Employee.empCount += 1
   
   def displayCount(self):
     print("Total Employee %d" % Employee.empCount)

   def displayEmployee(self):
      print("Name : ", self.name,  ", Salary: ", self.salary)

   def __repr__(self):#defines string representation of class 
      return "<name: %s, salary: %s>" % (self.name, self.salary)

In [49]:
emp1 = Employee("Zara", 2000)
emp2 = Employee("Manni", 5000)


emp1.displayEmployee()
print(emp1)
emp2.displayEmployee()
print(emp2)
print ("Total Employee %d" % Employee.empCount)

Name :  Zara , Salary:  2000
<name: Zara, salary: 2000>
Name :  Manni , Salary:  5000
<name: Manni, salary: 5000>
Total Employee 2


In [51]:
# Sorting Class Objects
people=[emp1,emp2]
def bySalary_key(person):
  return person.name

def byPerson_key(person):
  return str(person)

print(sorted(people, key = bySalary_key,reverse = True) )

print(sorted(people, key = byPerson_key))

[<name: Zara, salary: 2000>, <name: Manni, salary: 5000>]
[<name: Manni, salary: 5000>, <name: Zara, salary: 2000>]


In [52]:
#NUMPY
#NumPy is the fundamental package for scientific computing with Python
#Among other things, it provides a powerful n-dimensional array
#import numpy 
#import numpy as np
#np acts as a short name for numpy

In [55]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB 279.3 kB/s eta 0:00:56
   ---------------------------------------- 0.1/15.5 MB 459.5 kB/s eta 0:00:34
    --------------------------------------- 0.2/15.5 MB 908.0 kB/s eta 0:00:17
   - -------------------------------------- 0.4/15.5 MB 1.6 MB/s eta 0:00:10
   - -------------------------------------- 0.6/15.5 MB 2.1 MB/s eta 0:00:07
   -- ------------------------------------- 1.1/15.5 MB 3.1 MB/s eta 0:00:05
   ---- ----------------------------------- 1.9

In [56]:
import numpy as np
myarray = np.array([4,3,2])
mybigarray = np.array([[3, 2, 4], [3, 3, 2], [4, 5, 2]])
print(myarray)

[4 3 2]


In [57]:
print(mybigarray)

[[3 2 4]
 [3 3 2]
 [4 5 2]]


In [58]:
import numpy as np
a = np.array([1, 2, 3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [60]:
import numpy as np
dt=np.dtype(np.int32)
print(dt)
#int8, int16, int32, int64 can be replaced by equivalent string 'i1','i2','i4',i‘8’ etc.
dt = np.dtype('i4')
print(dt)

int32
int32


In [62]:
import numpy as np
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [64]:
import numpy as np
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print(a['age'])

[10 20 30]


In [65]:
#arange(start,stop,step)
print(np.arange(5))
print(np.arange(3,7,2))

[0 1 2 3 4]
[3 5]


In [66]:
print(np.ones(3))
print(np.ones((3,4)))

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [67]:
print(np.linspace(3,7,3))
#returns evenly spaced numbers in the given range. #np.linspace(start,stop,npoints)

[3. 5. 7.]


In [69]:
print(np.r_[np.array([1,2,3]), 0, 0, np.array([4,5,6])])#performs row concatenation

[1 2 3 0 0 4 5 6]


In [70]:
print(np.r_[1:4,0,4])

[1 2 3 0 4]


In [71]:
print(np.c_[np.array([1,2,3]), np.array([4,5,6])])

[[1 4]
 [2 5]
 [3 6]]


In [72]:
print(np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])])

[[1 2 3 0 0 4 5 6]]


In [73]:
a= np.arange(6).reshape(3,2)
print(a)
print(np.ndim(a))
print(np.size(a))
print(np.shape(a))
print(np.reshape(a,(2,3)))
print(np.ravel(a))
print(np.transpose(a))
print(a[::-1])#reverses the elements in the first dimension

[[0 1]
 [2 3]
 [4 5]]
2
6
(3, 2)
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 2 4]
 [1 3 5]]
[[4 5]
 [2 3]
 [0 1]]


In [75]:
a= np.arange(6).reshape(3,2)
print(a)
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.sum(a, axis=0))#sum of each column
print(np.sum(a, axis=1))#sum of each row
b = np.copy(a)#makes a deep copy
print(b)

[[0 1]
 [2 3]
 [4 5]]
0
5
15
[6 9]
[1 5 9]
[[0 1]
 [2 3]
 [4 5]]


In [76]:
#Matrix Operation
a= np.arange(6).reshape(3,2)
print(a)
b = np.arange(3,9).reshape(3,2)
print(b)
print(a+b)
print(a*b)

[[0 1]
 [2 3]
 [4 5]]
[[3 4]
 [5 6]
 [7 8]]
[[ 3  5]
 [ 7  9]
 [11 13]]
[[ 0  4]
 [10 18]
 [28 40]]


In [77]:
a= np.arange(6).reshape(3,2)
print(a)
c = np.arange(6).reshape(2,3)
print(c)
print(np.dot(a,c)) #Traditional matrix multiplication
print(pow(a,2))#computes every element raised to power 2
print(pow(2,a))#computes 2 raised to every element of matrix as power

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]
[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
[[ 0  1]
 [ 4  9]
 [16 25]]
[[ 1  2]
 [ 4  8]
 [16 32]]


In [79]:
#np.where() command
a = np.arange(5,10)
print(a)
print(np.where(a < 8))#returns indices of numbers<8
print(a[np.where(a < 8)]) #returns values <8

[5 6 7 8 9]
(array([0, 1, 2], dtype=int64),)
[5 6 7]


In [81]:
a = np.arange(4,10).reshape(2,3)
print(a)
print(np.where(a > 5))#in case of 2D array, it returns an array of row indices and an array of col indices
print(a[np.where(a > 5)])

[[4 5 6]
 [7 8 9]]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))
[6 7 8 9]


In [ ]:
#np.random.rand(matsize) produces uniformly distributed random numbers between 0 and 1 in an array of size matsize
#np.random.randn(matsize) produces zero mean, unit variance Gaussian random numbers
#np.random.normal(mean,stdev,matsize) produces Gaussian random numbers with specifed mean and standard deviation
#np.random.uniform(low,high,matsize) produces uniform random numbers between low and high
#np.random.randint(low,high,matsize) produces random integer values between low and high
#np.linalg.inv(a) Compute the inverse of (square) array a
#np.linalg.pinv(a) Compute the pseudo-inverse, which is defined even if a is not square
#np.linalg.det(a) Compute the determinant of a
#np.linalg.eig(a) Compute the eigenvalues and eigenvectors of a